
/**
 * returns formatted map of parameters
 */
def params(args = [:]) {
    if (!args instanceof Map) {
        args = [dir: args]
    }
    def argv = [
            dirs: [],
            name: 'Allure'
    ] << args
    def dirs = argv.dirs
    if (argv.dir) {
        dirs << argv.dir
    }
    if (!argv.dirs.empty) {
        argv.dirs = [ pwd() ]
    }
    return argv
}

/**
 * Publish HTML report with generated by allure
 * @param args named args - name, dir, dirs
 */
def publish(Map args = [:]) {
    args = params(args)
    def temp = files.tempDir('allure')
    dir(temp) {
        try {
            sh script: "allure generate --report-dir . --clean ${args.dirs.join(' ')}"
            publishHTML(target: [
                    allowMissing         : true,
                    alwaysLinkToLastBuild: false,
                    keepAll              : true,
                    reportDir            : '.',
                    reportFiles          : 'index.html',
                    reportName           : args.name,
            ])
        } finally {
            deleteDir()
        }
    }
}

/**
 * Publish HTML report with generated by allure
 * @param args named args - name, dir, dirs
 */
call(args = [:]) {
    publish(args)
}